Layout/DotPosition:
  EnforcedStyle: trailing

Metrics/BlockLength:
  Exclude:
    - 'Gemfile'
    - 'Rakefile'
    - 'spec/**/*.rb'

Metrics/ClassLength:
  Max: 150

Metrics/LineLength:
  Max: 120

Style/SymbolArray:
  Enabled: true

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: consistent_comma
