Metrics/LineLength:
  Max: 120

Style/SymbolArray:
  Enabled: true

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: consistent_comma

Layout/DotPosition:
  EnforcedStyle: trailing
