Layout/DotPosition:
  EnforcedStyle: trailing

Metrics/BlockLength:
  Exclude:
    - 'Gemfile'
    - 'Rakefile'
    - 'spec/**/*.rb'

Metrics/ClassLength:
  Max: 155

Metrics/LineLength:
  Max: 120

Style/SymbolArray:
  Enabled: true

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma

AllCops:
  TargetRubyVersion: 2.6

Layout/EmptyLineAfterGuardClause:
  Enabled: false
